default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tkg
  password: nhknokadai
  host: database-1.c5ku2ucw0qor.ap-southeast-2.rds.amazonaws.com
  port: 5432

development:
  <<: *default
  database: nhk_scraper_development

production:
  <<: *default
  database: nhk_scraper_production

